In [21]:
import pandas as pd

TOR_2 = pd.read_csv

In [32]:
import pandas as pd
TOR_2 = pd.read_csv
df = pd.read_csv
df = pd.read_csv (r'TOR_2.csv')

TOR_2 = df.shape




df.head(12)

   Postal Code       Borough                                      Neighborhood
0          M6E          York                               Caledonia-Fairbanks
1          M6M          York  Del Ray, Mount Dennis, Keelsdale and Silverthorn
2          M6C          York                                Humewood-Cedarvale
3          M6N          York                     Runnymede, The Junction North
4          M9N          York                                            Weston
5          M6K  West Toronto      Brockton, Parkdale Village, Exhibition Place
6          M6H  West Toronto                      Dufferin, Dovercourt Village
7          M6P  West Toronto                     High Park, The Junction South
8          M6J  West Toronto                          Little Portugal, Trinity
9          M6R  West Toronto                            Parkdale, Roncesvalles
10         M6S  West Toronto                                Runnymede, Swansea
11         M1S   Scarborough                                         Agincourt